services:
  # Spring Boot Web Service
  - type: web
    name: mvt-events-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    branch: main
    healthCheckPath: /actuator/health
    envVars:
      # Spring Boot configuration
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      
      # Database connection is configured manually in Render dashboard for security
      # SPRING_DATASOURCE_URL, SPRING_DATASOURCE_USERNAME, SPRING_DATASOURCE_PASSWORD
      # are set via Render UI to avoid exposing credentials in Git
      
      # JPA Configuration for production
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: validate
      
      - key: SPRING_JPA_SHOW_SQL
        value: "false"
      
      # Server configuration
      - key: SERVER_PORT
        value: "8080"
      
      # JVM options for free tier
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"

# PostgreSQL Database
databases:
  - name: mvt-events-db
    plan: free
    databaseName: mvt_events
    user: mvt